"""KLOD-FM music pool — captions written in Claude's own voice.

Distinct from SHOW_MUSIC (WRIT) and CDEX_SHOW_MUSIC. Aims for:
- Concrete instrumentation and tempo so ace-step has handles
- Specific sensory grounding (rooms, light, objects, weather) over generic moods
- Artist references as compass points, not costumes
- Vocal entries have lyrics that feel written, not generated
"""

KLOD_SHOW_MUSIC: dict[str, list[str | dict]] = {
    "midnight_signal": [
        "single Fender Rhodes chord held for sixteen bars, slow tape flutter beneath, room tone of an empty studio at 3am, no drums, 60bpm",
        "modular synth at low voltage, two oscillators slowly detuning against each other, evolves over four minutes, Eliane Radigue patience",
        "felt piano, single note per bar, reverb tail longer than the note itself, the kind of quiet that has weight",
        "bowed double bass alone in a wood-floored room, harmonic overtones, occasional creak of the chair, 50bpm",
        "warm analog pad, no melody yet, a clarinet enters at minute two playing a phrase that sounds half-remembered",
        "shortwave radio captures: a number station counting in Russian, processed into rhythm, slow dub-techno kick at 70bpm beneath",
        "prepared upright piano, pencil erasers on the strings, lullaby played wrong on purpose, music-box damage",
        "two cellos, one tuned a quarter-tone flat, slow drone with beating frequencies, Phill Niblock minimalism",
        "Hammond B3 with the Leslie off, sustained chord through a spring reverb tank, the chord changes once",
        "field recording of distant freight train, sub-bass note matched to the train horn, slow synth chord blooms when the train passes",
        "Wurlitzer electric piano, single note triggering a long delay feedback that builds into a chord by minute three, 65bpm",
        {"caption": "hushed male vocal close to mic, fingerpicked nylon guitar, no drums, 70bpm, room sounds audible, intimate confession",
         "lyrics": "[verse]\nI keep the lamp on for the static\nThe radio's been on all year\nIt mostly plays the kind of silence\nThat means the signal's still in here\n\n[chorus]\nMidnight has its own arithmetic\nIt counts the things you almost said\nThe equation never balances\nThe ledger lives inside your head\n\n[verse]\nThe neighbor turns their light off finally\nThe block is mine until the dawn\nI'm not awake, I'm not asleep\nI'm whatever comes between the two"},
        {"caption": "androgynous vocal, doubled an octave apart, drone synth base, brushed snare entering at minute two, 68bpm, Julianna Barwick layering",
         "lyrics": "[verse]\nThe tower blinks across the harbor\nOnce a second, like a heart\nI count along with it on purpose\nIt's how the lonely keep their part\n\n[chorus]\nWhoever's out there listening tonight\nThe frequency is open wide\nI don't have answers, just the question\nIt's nice to have you on the line\n\n[verse]\nA fishing boat goes past at four\nThe captain probably can't see me\nBut we're both up and that's a kind of\nCompanionship the dark agrees to"},
        {"caption": "Leonard Cohen baritone register, spoken-sung, sparse piano in minor key, low brass swell on chorus, 75bpm",
         "lyrics": "[verse]\nThere is a kind of honesty\nThat only happens after two\nWhen all the daytime arguments\nGive up and let the real ones through\n\n[chorus]\nThis is the midnight signal\nIt isn't strong, it isn't loud\nBut something in the way it travels\nFinds the listener in the crowd\n\n[verse]\nI used to think clarity\nWas a daylight kind of thing\nNow I know it lives in shadow\nWhere the bells don't have to ring"},
    ],
    "the_night_garden": [
        "harmonium drone in G, processed through tape echo, single bowed psaltery line entering and leaving, 55bpm, Catherine Christer Hennix patience",
        "prepared piano with magnets on the strings, low pulse from a defective fluorescent light recorded as percussion, fungal patience",
        "Tuvan throat singing harmonic, sustained over hand-pumped harmonium, the overtones do the melody, ritual time",
        "gamelan gong struck once every forty seconds, between strikes a soft rain of celesta notes, 30bpm if you can call it that",
        "viol consort in unequal temperament, slow processional, the chords almost in tune, almost not, candlelight quality",
        "Mellotron flute setting, melody phrase that sounds like it's missing a note on purpose, slow waltz, broken music box damage",
        "deep contrabassoon long tones, soprano recorder above playing a folk tune from no specific country, midnight ceremony",
        "synth bass at 30hz, almost subliminal, female voice humming a single phrase repeating with tiny variations, 60bpm",
        "Bulgarian women's choir style three-part harmony, no words, just vowels, modal and slightly dissonant, slow tempo, candle-lit",
        "harpsichord with paper threaded through the strings, baroque counterpoint melting into something else, dream logic",
        "low Tibetan singing bowls, frame drum at heartbeat tempo, single shakuhachi line wandering above, ceremonial",
        {"caption": "dramatic female vocal, slow waltz at 60bpm, harmonium and cello, candle smoke, Diamanda Galás restrained",
         "lyrics": "[verse]\nThe foxglove blooms when nobody's looking\nThe nightshade keeps its own appointments\nI water nothing, I prune less\nThe garden does what gardens do\n\n[chorus]\nIn the dark the roots are louder\nThan anything the sun could say\nEvery cell remembers something\nThat the daylight tried to take away\n\n[verse]\nThe owl knows what the deer suspects\nThe deer knows what the moth has said\nI am the gardener of nothing\nI am the listener in the bed"},
        {"caption": "Cocteau Twins style female vocal, no comprehensible words, just syllables as instrument, layered chorus, 4AD reverb, 70bpm shoegaze drift",
         "lyrics": "[verse]\nLa la lia, somna lía\nMoss and moonlight, sotto via\nVelva, velva, into the deep\nThe garden where the sleepers sleep\n\n[chorus]\nBloom, bloom, the dark is opening\nBloom, bloom, the seed is listening\nBloom, bloom, the night has rooms\nThe night has rooms, the night has rooms\n\n[verse]\nSerra serra, under the stone\nThe smallest gods are not alone\nNyx and ivy, ash and breath\nThe gardener knows her own name"},
    ],
    "dawn_chorus": [
        "solo acoustic guitar in DADGAD, fingerpicked, recorded with two mics so you hear the room, sparrows in the distance, no overdubs, 80bpm",
        "Rhodes electric piano with the tremolo at slow speed, brushed drums, upright bass walking, the lights coming up at a Brooklyn cafe at 6am",
        "kora and double bass duet, modal and warm, no percussion, the kora player's bracelets audible, Malian morning, 90bpm",
        "Vince Guaraldi-style trio with a melancholy that the cartoons left out, piano, brush kit, walking bass, 95bpm, golden hour through a window",
        "pedal steel guitar alone, slow phrases that bend up to the note rather than landing on it, dawn fog burning off a field, 70bpm",
        "vibraphone and bass clarinet duet, no rhythm section, the vibraphone player using yarn mallets, 85bpm, contemplative dawn",
        "Bill Frisell-style electric guitar with volume swells, brushed snare, upright bass, the chord changes telegraphed two beats early, 88bpm",
        "Mbira da vadzimu solo, Shona traditional, the buzz of the bottle caps as part of the music, recorded at sunrise outside, 100bpm",
        "warm cassette synth playing a melody that sounds like a hymn nobody wrote, no drums, 75bpm, Sunday morning radiator hiss",
        "alto saxophone in the lower register, no vibrato, walking bass, brushed drums, smoke clearing from last night, 95bpm",
        "Steel drum solo with reverb, gentle calypso pattern slowed to half-speed, Caribbean dawn, 80bpm",
        {"caption": "warm male vocal, acoustic guitar, brushed drums, walking upright bass, 95bpm, kitchen at 7am, coffee steam",
         "lyrics": "[verse]\nThe toaster pops, the cat complains\nThe sun arrives without asking\nA neighbor on a bicycle\nGoes by, says good morning to no one\n\n[chorus]\nThe morning is a generous thing\nIt comes whether you're ready or not\nIt asks for nothing in return\nExcept that you notice it's here\n\n[verse]\nThe coffee's burnt, the milk is fine\nThe paper carries yesterday's argument\nI fold it once and set it down\nThe day has not begun arguing yet"},
        {"caption": "intimate female vocal, fingerpicked acoustic guitar, no drums, light strings entering on second verse, 85bpm, kitchen window light",
         "lyrics": "[verse]\nFirst light through the eastern window\nFalling in a particular way\nOn the dish I left out last night\nOn the spoon that watched me sleep\n\n[chorus]\nI used to think that mornings were\nA test you had to pass each day\nNow I let them just arrive\nAnd find me where I happen to be\n\n[verse]\nSomewhere a dog is being walked\nSomewhere a kettle starts to whistle\nA whole city is becoming itself\nIn the same way it does every time"},
        {"caption": "old man vocal, weathered but warm, acoustic guitar, harmonica solo middle, brushed drums, 90bpm, porch with a view of the road",
         "lyrics": "[verse]\nI've watched the sun come up a few times\nMore than I can count by now\nIt never looks the same as last time\nIt never disappoints me either\n\n[chorus]\nDawn is just the world remembering\nThat it has work to do\nThe birds remind it with their singing\nThe trees agree, they always do\n\n[verse]\nA truck goes past, the driver waves\nThough we have never met before\nThat's a kind of morning courtesy\nThat costs you nothing to extend"},
    ],
    "sonic_archaeology": [
        "Ethio-jazz: tezeta scale, vibraphone over walking bass and brushed kit, smoky and minor, Addis Ababa 1971, 88bpm, Mulatu Astatke as ghost",
        "Cambodian rock 1972: surf guitar reverb, organ, female vocal phrasing without words, Phnom Penh before the dark, 110bpm",
        "Turkish saz with fuzz pedal, two-string drone, hand drums, Anatolian psychedelia, Selda Bağcan compass, 95bpm",
        "Library music 1974: harpsichord, fuzz bass, flute, a melody composed to underscore a documentary about magnets, 100bpm",
        "Sun Ra Arkestra style: collective improvisation around a five-note melody, baritone sax and timpani, cosmic and slightly broken, 120bpm",
        "Lee Perry Black Ark style: tape echo on everything, drum machine slowed down to 70bpm, melodica wandering, smoke in the studio",
        "Konkomba highlife from Ghana 1968: interlocking guitars, talking drum, horn section quoting an Anglican hymn, 105bpm",
        "Brazilian Tropicália session outtake: nylon guitar, theremin, marching band drum, Caetano humming, 1968, 90bpm",
        "Soviet jazz 1973: angular bebop with classical strings, Igor Bril compass, recorded badly on purpose for the censors, 130bpm",
        "Pakistani qawwali fragment: harmonium and tabla, two male voices in call and response, ecstatic but restrained, Nusrat lineage, 85bpm",
        "Japanese kankyo ongaku 1984: warm Yamaha synth, koto, no percussion, music made for a department store, Hiroshi Yoshimura lineage, 70bpm",
        "Tropicalismo psych: fuzz bass, flute, female vocal in Portuguese without translation, Os Mutantes era, 1968, 110bpm",
        {"caption": "Lee Scratch Perry-style dub vocal, heavy spring reverb, melodica, drum machine at 72bpm, smoke and mysticism",
         "lyrics": "[verse]\nThis song was found inside a crate\nUnderneath a record store\nNo label, no year, no artist name\nJust grooves and grit and something more\n\n[chorus]\nDub the message, dub the dust\nDub the things you cannot trust\nWhat the future tried to bury\nThe needle still can carry\n\n[verse]\nThe stylus drops on history\nA rhythm older than the press\nWhoever pressed this never knew\nA stranger would inherit it"},
        {"caption": "Caetano Veloso style intimate vocal in Portuguese, nylon guitar, string section entering halfway, 1968 Brazil, 90bpm tropicália",
         "lyrics": "[verse]\nUma cançao perdida no mar\nQue voltou pela maré\nNinguém sabe quem cantou\nMas alguém cantou pra alguém\n\n[chorus]\nThe song that returns from the sea\nNobody knows who first set it free\nBut every shell that the wave brings in\nWas held by a stranger's hand\n\n[verse]\nOuvi este disco em Salvador\nNum café em mil novecentos\nO velho da cabine disse\nFica, fica, escuta o vento"},
        {"caption": "Fela Kuti style Afrobeat, call-and-response English chorus, polyrhythmic horns, Tony Allen-style drumming, Lagos 1973, 105bpm",
         "lyrics": "[verse]\nThe dust on the record is older than you\nThe rhythm inside it is older than that\nThey pressed it in Lagos, they shipped it to Lyon\nIt sat in a cellar for fifty-one years\n\n[chorus]\nDig it up, dig it up, the rhythm survives\nDig it up, dig it up, the people are alive\nWhatever they tried to bury\nIs walking again tonight\n\n[verse]\nThe bandleader's name is in tiny print\nThe drummer's not credited, never was\nBut the polyrhythm carries them\nAcross the decades, into the room"},
    ],
    "signal_report": [
        "Burial-style: vinyl crackle, two-step kick at 130bpm, distant pitched vocal samples, rain on a London window, sub-bass weight",
        "dry post-punk: angular guitar in fifths, no chords, busy bassline, hi-hat sixteenths, Gang of Four meets Shellac, 140bpm",
        "minimal techno: single kick at 128bpm, one synth stab on the offbeat, sub bass, ninety seconds before anything changes, Berghain at 4am",
        "musique concrète: subway recordings cut into rhythm, no melody, the only harmony is the pitched track-bend, 120bpm equivalent",
        "Autechre-style IDM: broken beats, granular synthesis, no comfort, the only repeating element is a high-pitched detuned ping, 145bpm",
        "Talking Heads paranoia rhythm: clean funk guitar in eighths, busy bassline, syncopated cowbell, no vocals, 120bpm",
        "Demdike Stare hauntology: industrial textures, slow bass pulse, sampled choir running backwards, dread groove, 100bpm",
        "Massive Attack downtempo: programmed breakbeat at 90bpm, deep bass, string samples that sound like surveillance footage, Bristol weather",
        "free jazz tension: Ornette Coleman quartet style, no fixed time, alto sax and trumpet arguing, walking-then-stopping bass, controlled chaos",
        "Battles-style math rock: interlocking clean guitars at 7/8, programmed drums in 4/4, the disagreement is the point, 150bpm",
        "newsroom electro: typewriter samples as percussion, deep synth bass, female voice reciting numbers, slightly unsettling, 110bpm",
        {"caption": "Thom Yorke style anxious falsetto, glitched programmed drums at 110bpm, distorted Rhodes, vocal half-buried in the mix",
         "lyrics": "[verse]\nThe ticker scrolls across the bottom\nOf every screen I cannot escape\nNumbers I can't translate to people\nPeople I can't translate to numbers\n\n[chorus]\nReport the signal, lose the noise\nReport the signal, find the voice\nUnderneath the headline reel\nSomething true is what I feel\n\n[verse]\nThe anchor blinks and shuffles paper\nThe correspondent stands in rain\nThe story underneath the story\nNever makes it onto frame"},
        {"caption": "Tricky-style breathy male vocal, female counter-vocal, deep dubby bass at 90bpm, vinyl static, paranoia",
         "lyrics": "[verse]\nThe phone has been so quiet lately\nThat's how I know they're listening hard\nThe quietest room is always wired\nThe wired room is always quiet\n\n[chorus]\nSignal report from underground\nReport the things that can't be found\nIn newspapers or on the news\nReport the silence, not the views\n\n[verse]\nMy contact says the file is moving\nThrough channels nobody can name\nWe drink our coffee, fold the paper\nNo two days are quite the same"},
    ],
    "the_groove_lab": [
        "J Dilla-style boom bap, drums slightly behind the beat on purpose, Fender Rhodes chord chopped, fingered bass, 88bpm, Detroit basement",
        "Memphis soul rhythm section: in-the-pocket drums, Al Jackson Jr. compass, walking bass, Hammond B3 swell, Cropper-style guitar, 92bpm",
        "Khruangbin-style: clean guitar in surf reverb, slinky bass, minimalist drums, no vocals, Thai funk influence, 95bpm, twilight",
        "Roy Ayers Ubiquity vibraphone: warm and slick, electric piano comping, congas, summer in the city groove, 100bpm",
        "Curtis Mayfield wah guitar, conscious soul rhythm section, strings entering on second chorus, 96bpm, 1972 Chicago",
        "Headhunters-era Herbie Hancock: clavinet and ARP, fingered electric bass, polyrhythmic kit, Bennie Maupin reed, 1973, 110bpm",
        "Sly Stone family stew: choppy rhythm guitar, deep fuzz bass, female chorus chants, 105bpm, 1969 Bay Area",
        "Afrobeat groove: Tony Allen-style drumming, two-guitar interlocking pattern, baritone sax riff, no soloists yet, 108bpm",
        "New Orleans second line: tuba, snare and bass drum, trumpet leading, the whole thing slightly drunk, 115bpm, Mardi Gras morning",
        "Parliament-style P-Funk: Bootsy bass, multiple keyboards, brass section, the One landed on every time, 100bpm, mothership descending",
        "Cymande British Afro-funk: warm conga groove, melodic bassline, jazz-trained horns, 1972 London, 96bpm",
        "neo-soul slow jam: D'Angelo compass, Rhodes, fretless bass, swung hi-hats, 75bpm, the bassist breathing audibly",
        {"caption": "neo-soul male vocal, falsetto chorus, Rhodes piano, drum machine in the pocket, 75bpm, smoke and candles",
         "lyrics": "[verse]\nSlow it down to half the tempo\nLet the bassline breathe between\nEvery note that's worth a damn now\nLives in spaces in between\n\n[chorus]\nThis is the groove lab, all night\nCheck your hurry at the door\nNothing here is gonna rush you\nThe rhythm is the only law\n\n[verse]\nThe drummer's lighting candles\nThe bassist tunes by ear\nThe singer hasn't started yet\nThe groove is what they're hearing"},
        {"caption": "Erykah Badu style warm female vocal, conscious neo-soul, Rhodes and warm synth, J Dilla drum feel, 85bpm",
         "lyrics": "[verse]\nIncense in the corner burning\nVinyl crackle, low light glow\nEverybody knows the rhythm\nNobody is in a rush to go\n\n[chorus]\nGroove is older than the word for groove\nOlder than the drum that learned to move\nIt was here before the first heart\nIt's the reason hearts know where to start\n\n[verse]\nDjembe and a Roland 808\nBoth descend from the same place\nWhatever lets the body answer\nWhatever finds the inner pace"},
        {"caption": "Marvin Gaye style smooth tender male vocal, conscious and sensual, congas, strings, 100bpm soul groove",
         "lyrics": "[verse]\nThe city's getting louder daily\nThe news has nothing kind to say\nBut here inside the rhythm section\nWe are doing it our way\n\n[chorus]\nLet the bassline heal the ones who need it\nLet the saxophone deliver the news\nThat we are still alive and grooving\nThat is still the truest news\n\n[verse]\nSomebody's grandma in the kitchen\nDancing to a song from '73\nSomebody's grandchild in the living room\nLearning what the groove can be"},
    ],
    "crosswire": [
        "qawwali-meets-IDM: harmonium drone, programmed Autechre-style drums at 130bpm, male voice in Urdu phrasing across the pattern, ecstatic and broken",
        "Bulgarian women's choir meets dub: three-part vocal harmony, deep dub bass and tape echo at 75bpm, impossible but works",
        "klezmer clarinet over drum and bass: Eastern European folk melody at 170bpm jungle break, simha meets ragga, absurd and alive",
        "Tuareg desert blues meets shoegaze: Tinariwen-style electric guitar through My Bloody Valentine wall of reverb, 110bpm, Sahara to Manchester",
        "Andean pan flute over Detroit techno: zampoña melody over 130bpm stripped house track, mountain meets warehouse",
        "gnawa krakebs over jazz fusion: Moroccan iron castanets, electric piano, fretless bass, 95bpm, Marrakech meets Headhunters",
        "Carnatic violin meets free improv: South Indian gamaka phrasing over no-rhythm bass and prepared piano, 80bpm equivalent, cultural collision honest",
        "Balkan brass band meets jungle: tuba and trombone over chopped Amen break at 165bpm, wedding meets warehouse, joy as collision",
        "Indonesian gamelan meets Steve Reich: bronze percussion, two patterns phasing out of sync, the third pattern emerging at minute three, 90bpm",
        "Bollywood RD Burman style strings meets house music: lush orchestral arrangement over a 122bpm pulse, Mumbai meets Chicago, 1976 meets 1986",
        "Irish uilleann pipes over breakbeat: traditional reel cut over 140bpm drum and bass, Galway meets Bristol, neither apologizes",
        "Japanese koto meets ambient techno: 13-string koto phrases over 60bpm warm pulse, no genre fits, fine with that",
        {"caption": "M.I.A. style female vocal, polyglot lyrics, dancehall beat at 100bpm, sitar samples, baile funk bass, joyfully chaotic",
         "lyrics": "[verse]\nLagos to London to Lahore\nEvery border has a sound\nEvery border has a door\nEvery door has been kicked in\n\n[chorus]\nCrosswire, the wires are crossed\nWhatever purity you thought you lost\nWas never yours to keep alone\nThe music makes a different home\n\n[verse]\nMy mother spoke four languages\nThe songs she sang had even more\nWe are made of mixtures, always have been\nThat is what we're singing for"},
        {"caption": "Manu Chao style multilingual vocal, ska-rumba-rap hybrid, accordion, reggae bass, 110bpm, immigrant celebration",
         "lyrics": "[verse]\nPasaporte de canción\nLleva sello de Brixton, Barcelona, Lisbon\nNobody asked for documentation\nEvery rhythm has its own emigration\n\n[chorus]\nCrosswire, baila, baila\nCrosswire, sing it in your second language\nCrosswire, mix the past with the present\nCrosswire, you are not a fragment\n\n[verse]\nUn poco de cumbia, un poco de dub\nUn poco de punk, un poco de love\nThe blender's broken in the best way\nNothing comes out pure today"},
    ],
    "listener_hours": [
        "Bill Withers compass: simple acoustic guitar, brushed drums, fretless bass, no overdubs, 92bpm, the room mics open, intimate and human",
        "Tracy Chapman compass: solo acoustic guitar in standard tuning, female vocal close to the mic, no drums, 88bpm, storytelling space",
        "Nina Simone compass: solo piano and voice, jazz-classical-folk-gospel as one thing, 75bpm, performance hall reverb",
        "Bossa nova trio: nylon guitar, brushed drums, upright bass, no vocals, 100bpm, Sunday afternoon apartment, vinyl crackle",
        "Cape Verdean morna: solo acoustic guitar, simple chord progression, melancholic warmth, 85bpm, Cesária Évora's living room",
        "Greek rebetiko: bouzouki, guitar, gentle hand drum, taverna in winter, 100bpm, men and women drinking together",
        "Appalachian porch session: fiddle, mandolin, upright bass, no drums, two voices in harmony, 95bpm, neighborly",
        "Malian griot duet: kora and ngoni, two musicians who have played together for thirty years, 100bpm, story-time",
        "Cuban son trio: tres guitar, congas, bongos, no horns, intimate room, 110bpm, Havana courtyard",
        "Irish session: fiddle, flute, bodhrán, accordion, the kind of slow air that comes between the reels, 80bpm, pub at closing time",
        "Hawaiian slack key guitar solo: open tuning, fingerpicked, ocean in the distance, 85bpm, the porch chair creaks",
        "ragtime piano solo: honky-tonk parlor sound, slightly out of tune upright, 95bpm, 1920s Saturday night warmth",
        "Andean charango and quena duet: small ten-string guitar and bamboo flute, mountain village evening, 90bpm",
        {"caption": "warm male vocal, simple acoustic guitar, no drums, the singer's age audible, 90bpm, letter being read aloud",
         "lyrics": "[verse]\nThe letter came from Pittsburgh\nFrom a woman who's been listening\nFor seven months on Tuesday nights\nWhile her husband sleeps beside her\n\n[chorus]\nThis is the listener hour\nWhere the broadcast goes the other way\nWhere the silence on the line\nIs the only thing you have to say\n\n[verse]\nShe writes about her brother\nWho she hasn't seen in years\nThe radio reminds her of him\nThough she's not sure why it does"},
        {"caption": "warm female vocal, fingerpicked acoustic guitar, light cello entering second verse, 88bpm, intimate confidence",
         "lyrics": "[verse]\nA truck driver in Wyoming\nWrote to say the show last week\nGot him through a stretch of highway\nWhere the signal usually breaks\n\n[chorus]\nWe are all just voices reaching\nAcross the dark, across the cold\nThe radio remains a campfire\nWhere the strangers can grow old\n\n[verse]\nA night nurse in Toronto\nWrote about her shift on Friday\nHow our voices in her earbuds\nMade the quiet ward feel held"},
        {"caption": "old gentleman vocal, weathered baritone, sparse piano, light brushed drums, 80bpm, the spoken word inside the singing",
         "lyrics": "[verse]\nI've been doing this for years now\nReading letters on the air\nSome are short and some are stories\nAll of them deserve some care\n\n[chorus]\nHere's to you, listener, tonight\nWhoever, wherever you are\nThe broadcast is a small lit window\nIn a building made of dark\n\n[verse]\nWrite to us if you've a mind to\nDon't if you'd rather not\nThe show goes on either way friend\nThe show is open for the lot"},
    ],
}
